#' Include JavaScript support for Word 'cross-reference' type link clicks
#'
#' This function registers the JavaScript dependency that enables click
#' handling for links generated by \code{word_html_insert_link()}.
#'
#' It should be added once in your Shiny UI (or R Markdown document),
#' typically near the top level. The dependency includes an event handler
#' that listens for clicks on elements with the class \code{word-html-link}
#' and forwards their \code{data-link} value to Shiny as
#' \code{input$word_html_link}.
#'
#' @return An \code{htmltools::htmlDependency} object.
#'
#' @examples
#' \dontrun{
#' # Example: Using word_html_insert_link() inside a Shiny navbarPage app
#'
#' library(shiny)
#' library(snappack)
#'
#' # A small HTML fragment with a span matching the default selector
#' html <- '<p>Go to <span class="Crossreference">Recommendations</span></p>'
#'
#' # Insert a link with a specific link_value to send to Shiny
#' doc <- word_html_insert_link(
#'   html,
#'   pattern = "Recommendations",
#'   link_value = "recommendations_panel"
#' )
#'
#' ui <- navbarPage(
#'   id = "navbar",
#'   "Example App",
#'
#'   # Add the JS event handler ONCE at the top level
#'   header = use_word_html_links(),
#'
#'   tabPanel("Home",
#'            # Include the modified HTML (now containing <a class="word-html-link">)
#'            HTML(as.character(doc))
#'   ),
#'
#'   tabPanel("Recommendations", value = "recommendations_panel",
#'            h3("Recommendation Page Content")
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'
#'   # React to clicks generated by word_html_insert_link()
#'   observeEvent(input$word_html_link, {
#'     print(input$word_html_link)
#'     # Switch the navbarPage to the panel indicated by link_value
#'     updateNavbarPage(session, inputId = "navbar",
#'                      selected = input$word_html_link)
#'   })
#' }
#'
#' shinyApp(ui, server)
#' }
#'
#' @export
use_word_html_links <- function() {
  htmltools::htmlDependency(
    name = "word-html-link-handler",
    version = "1.0.0",
    src = "www",
    package = "snappack",
    script = "word-html-link-handler.js"
  )
}
