#' Insert HTML links into elements of a Word-exported HTML document
#'
#' This function wraps selected HTML nodes in an <a> tag with a generic
#' CSS class (default: "word-html-link") so that JavaScript can detect
#' click events and optionally forward them to Shiny.
#'
#' @param html A file path, character string containing HTML, or a
#'   parsed xml_document.
#' @param pattern Optional. A regex pattern to match against the text
#'   content of each target node. If NULL, all matching nodes are wrapped.
#' @param link_value Optional value to store in a `data-link` attribute
#'   on the generated <a> tag. If NULL, the node's text content is used.
#' @param selector A CSS selector used to locate candidate elements.
#'   Defaults to "span.Crossreference".
#' @param class CSS class to assign to generated links. Defaults to
#'   "word-html-link". Provided JS event handler requires links to be of
#'   this class. See \code{use_word_html_links()}.
#'
#' @return A modified xml_document with matching elements wrapped in
#'   <a> tags. Does not write to disk.
#'
#' @examples
#' \dontrun{
#' # Example: Using word_html_insert_link() inside a Shiny navbarPage app
#'
#' library(shiny)
#' library(snappack)
#'
#' # A small HTML fragment with a span matching the default selector
#' html <- '<p>Go to <span class="Crossreference">Recommendations</span></p>'
#'
#' # Insert a link with a specific link_value to send to Shiny
#' doc <- word_html_insert_link(
#'   html,
#'   pattern = "Recommendations",
#'   link_value = "recommendations_panel"
#' )
#'
#' ui <- navbarPage(
#'   id = "navbar",
#'   "Example App",
#'
#'   # Add the JS event handler ONCE at the top level
#'   header = use_word_html_links(),
#'
#'   tabPanel("Home",
#'            # Include the modified HTML (now containing <a class="word-html-link">)
#'            HTML(as.character(doc))
#'   ),
#'
#'   tabPanel("Recommendations", value = "recommendations_panel",
#'            h3("Recommendation Page Content")
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'
#'   # React to clicks generated by word_html_insert_link()
#'   observeEvent(input$word_html_link, {
#'     print(input$word_html_link)
#'     # Switch the navbarPage to the panel indicated by link_value
#'     updateNavbarPage(session, inputId = "navbar",
#'                      selected = input$word_html_link)
#'   })
#' }
#'
#' shinyApp(ui, server)
#' }
#' @export
word_html_insert_link <- function(
    html,
    pattern    = NULL,
    link_value = NULL,
    selector   = "span.Crossreference",
    class      = "word-html-link"
) {

  # ---- Parse input ----------------------------------------------------------
  doc <- if (is.character(html) && length(html) == 1 && file.exists(html)) {
    xml2::read_html(html)
  } else if (is.character(html)) {
    xml2::read_html(paste(html, collapse = "\n"))
  } else {
    html  # assume xml_document
  }

  # ---- Find target nodes ----------------------------------------------------
  nodes <- rvest::html_elements(doc, selector)

  if (length(nodes) == 0) {
    warning(sprintf("No elements found for selector '%s'", selector))
    return(doc)
  }

  # ---- Wrap matching nodes in <a> tags -------------------------------------
  for (node in nodes) {

    # Skip if already wrapped
    if (length(rvest::html_elements(node, "a")) > 0) next

    # Extract text
    txt <- xml2::xml_text(node)

    # Optional pattern filter
    if (!is.null(pattern) && !stringr::str_detect(txt, pattern)) next

    # Determine link value
    value <- if (!is.null(link_value)) link_value else stringr::str_squish(txt)

    # Capture original content
    original_children <- xml2::xml_contents(node)

    # Create <a> containing the node's content
    a <- xml2::xml_replace(
      node,
      "a",
      href = "#",
      class = class,
      `data-link` = value
    )

    lapply(original_children, function(x) xml2::xml_add_child(a, x))

  }

  doc
}
