#' Insert HTML links into elements of a Word‑exported HTML document
#'
#' This function inserts clickable HTML links in one of two ways:
#'
#' **1. XML mode (default):**
#' If a CSS `selector` is provided (the default), matching elements in the
#' parsed HTML document are wrapped in `<a>` tags.
#' If no elements match the selector, the function performs no linking and
#' returns the document unchanged.
#'
#' **2. Text‑replacement mode:**
#' If `selector = NULL`, the function does not look for HTML nodes. Instead,
#' any substring matched by `pattern` is replaced directly in the HTML using
#' `<a>` tags.
#' This mode allows linking arbitrary text fragments within HTML elements.
#'
#' @param html A file path, character string containing HTML, or an
#'   xml_document object.
#' @param pattern Optional. A regex pattern used to identify text to wrap in a
#'   link. If NULL, all nodes matching the selector are linked.
#' @param link_value Optional value stored in the `data-link` attribute. If
#'   NULL, the matched text (in text‑mode) or node text (in XML‑mode) is used.
#' @param selector CSS selector for locating candidate elements.
#'   Set to `NULL` to enable text‑replacement mode. Defaults to
#'   `"span.Crossreference"`.
#' @param class CSS class assigned to the generated `<a>` tag.
#'   Defaults to `"word-html-link"`.
#' @param href The `href` attribute to apply to generated `<a>` tags.
#'   Defaults to `"#"`. May be set to any URL or internal reference.
#'
#' @return An xml_document with modified content. Does not write to disk.
#'

#' @examples
#' \dontrun{
#' # Example: Using word_html_insert_link() inside a Shiny navbarPage app
#'
#' library(shiny)
#' library(snappack)
#'
#' # A small HTML fragment with a span matching the default selector
#' html <- '<p>Go to <span class="Crossreference">Recommendations</span></p>'
#'
#' # Insert a link with a specific link_value to send to Shiny
#' doc <- word_html_insert_link(
#'   html,
#'   pattern = "Recommendations",
#'   link_value = "recommendations_panel"
#' )
#'
#' ui <- navbarPage(
#'   id = "navbar",
#'   "Example App",
#'
#'   # Add the JS event handler ONCE at the top level
#'   header = use_word_html_links(),
#'
#'   tabPanel("Home",
#'            # Include the modified HTML (now containing <a class="word-html-link">)
#'            HTML(as.character(doc))
#'   ),
#'
#'   tabPanel("Recommendations", value = "recommendations_panel",
#'            h3("Recommendation Page Content")
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'
#'   # React to clicks generated by word_html_insert_link()
#'   observeEvent(input$word_html_link, {
#'     print(input$word_html_link)
#'     # Switch the navbarPage to the panel indicated by link_value
#'     updateNavbarPage(inputId = "navbar",
#'                      selected = input$word_html_link)
#'   })
#' }
#'
#' shinyApp(ui, server)
#' }
#' @export

word_html_insert_link <- function(
    html,
    pattern    = NULL,
    link_value = NULL,
    selector   = "span.Crossreference",
    class      = "word-html-link",
    href       = "#"
) {

  # ---- Parse input ----------------------------------------------------------
  doc <- if (is.character(html) && length(html) == 1 && file.exists(html)) {
    xml2::read_html(html)
  } else if (is.character(html)) {
    xml2::read_html(paste(html, collapse = "\n"))
  } else {
    html  # assume xml_document
  }


  # ---- MODE 1: XML MODE (selector provided) ---------------------------------
  if (!is.null(selector)) {

    nodes <- rvest::html_elements(doc, selector)

    if (length(nodes) == 0) {
      message(sprintf("No elements matched selector '%s'. No links inserted.", selector))
      return(doc)
    }

    for (node in nodes) {

      # Skip if node already contains <a>
      if (length(rvest::html_elements(node, "a")) > 0) next

      txt <- xml2::xml_text(node)

      # Optional pattern filter
      if (!is.null(pattern) && !stringr::str_detect(txt, pattern)) next

      # Determine link value
      value <- if (!is.null(link_value)) link_value else stringr::str_squish(txt)

      # Capture children
      original_children <- xml2::xml_contents(node)

      # Replace node with <a>
      a <- xml2::xml_replace(
        node,
        "a",
        href = href,
        class = class,
        `data-link` = value
      )

      # Re‑attach children
      lapply(original_children, function(x) xml2::xml_add_child(a, x))
    }

    return(doc)
  }

  # ---- MODE 2: TEXT‑REPLACEMENT MODE (selector = NULL) ----------------------
  if (is.null(pattern)) {
    stop("Text‑replacement mode requires a non‑NULL 'pattern'.")
  }

  html_str <- as.character(doc)

  new_str <- stringr::str_replace_all(
    html_str,
    pattern,
    function(x) {
      paste0(
        "<a href='", href, "' class='", class,
        "' data-link='",
        if (is.null(link_value)) x else link_value,
        "'>",
        x,
        "</a>"
      )
    }
  )

  xml2::read_html(new_str)

}
